-- Seed data for FitJournal
-- Run this after creating the schema

-- Insert predefined exercises
INSERT INTO exercises (id, name, category, muscle_group, equipment, is_custom) VALUES
('bench-press', 'Press de banca', 'chest', 'Pectoral', 'barbell', false),
('incline-bench', 'Press inclinado', 'chest', 'Pectoral superior', 'barbell', false),
('dumbbell-flyes', 'Aperturas con mancuernas', 'chest', 'Pectoral', 'dumbbell', false),
('push-ups', 'Flexiones', 'chest', 'Pectoral', 'bodyweight', false),
('dips', 'Fondos', 'chest', 'Pectoral / Tríceps', 'bodyweight', false),
('cable-crossover', 'Cruces en polea', 'chest', 'Pectoral', 'cable', false),
('pull-ups', 'Dominadas', 'back', 'Dorsal', 'bodyweight', false),
('chin-ups', 'Dominadas supinas', 'back', 'Dorsal / Bíceps', 'bodyweight', false),
('deadlift', 'Peso muerto', 'back', 'Espalda baja / Isquios', 'barbell', false),
('barbell-row', 'Remo con barra', 'back', 'Dorsal / Trapecio', 'barbell', false),
('dumbbell-row', 'Remo con mancuerna', 'back', 'Dorsal', 'dumbbell', false),
('lat-pulldown', 'Jalón al pecho', 'back', 'Dorsal', 'machine', false),
('face-pulls', 'Face pulls', 'back', 'Deltoides posteriores', 'cable', false),
('squat', 'Sentadilla', 'legs', 'Cuádriceps / Glúteos', 'barbell', false),
('front-squat', 'Sentadilla frontal', 'legs', 'Cuádriceps', 'barbell', false),
('leg-press', 'Prensa de piernas', 'legs', 'Cuádriceps / Glúteos', 'machine', false),
('romanian-deadlift', 'Peso muerto rumano', 'legs', 'Isquiotibiales / Glúteos', 'barbell', false),
('leg-curls', 'Curl femoral', 'legs', 'Isquiotibiales', 'machine', false),
('leg-extensions', 'Extensión de cuádriceps', 'legs', 'Cuádriceps', 'machine', false),
('calf-raises', 'Elevación de gemelos', 'legs', 'Gemelos', 'machine', false),
('lunges', 'Zancadas', 'legs', 'Cuádriceps / Glúteos', 'dumbbell', false),
('bulgarian-split-squat', 'Sentadilla búlgara', 'legs', 'Cuádriceps / Glúteos', 'dumbbell', false),
('overhead-press', 'Press militar', 'shoulders', 'Deltoides', 'barbell', false),
('dumbbell-press', 'Press con mancuernas', 'shoulders', 'Deltoides', 'dumbbell', false),
('lateral-raises', 'Elevaciones laterales', 'shoulders', 'Deltoides laterales', 'dumbbell', false),
('rear-delt-flyes', 'Pájaros posteriores', 'shoulders', 'Deltoides posteriores', 'dumbbell', false),
('upright-row', 'Remo al mentón', 'shoulders', 'Deltoides / Trapecio', 'barbell', false),
('barbell-curl', 'Curl con barra', 'arms', 'Bíceps', 'barbell', false),
('dumbbell-curl', 'Curl con mancuerna', 'arms', 'Bíceps', 'dumbbell', false),
('hammer-curl', 'Curl martillo', 'arms', 'Bíceps / Braquial', 'dumbbell', false),
('tricep-pushdown', 'Pushdown tríceps', 'arms', 'Tríceps', 'cable', false),
('skullcrushers', 'Extensión de tríceps', 'arms', 'Tríceps', 'barbell', false),
('close-grip-bench', 'Press cerrado', 'arms', 'Tríceps', 'barbell', false),
('plank', 'Plancha', 'core', 'Abdominales', 'bodyweight', false),
('hanging-leg-raise', 'Elevación de piernas', 'core', 'Abdominales inferiores', 'bodyweight', false),
('crunches', 'Abdominales', 'core', 'Recto abdominal', 'bodyweight', false),
('russian-twists', 'Giros rusos', 'core', 'Oblicuos', 'bodyweight', false),
('ab-wheel', 'Rueda abdominal', 'core', 'Abdominales', 'none', false),
('muscle-up', 'Muscle-up', 'calisthenics', 'Espalda / Pecho', 'bodyweight', false),
('handstand', 'Parada de manos', 'calisthenics', 'Hombros / Core', 'bodyweight', false),
('planche', 'Planche', 'calisthenics', 'Hombros / Core', 'bodyweight', false),
('front-lever', 'Front lever', 'calisthenics', 'Dorsal / Core', 'bodyweight', false),
('l-sit', 'L-sit', 'calisthenics', 'Core / Tríceps', 'bodyweight', false),
('dragon-flag', 'Dragon flag', 'calisthenics', 'Core', 'bodyweight', false)
ON CONFLICT (id) DO NOTHING;
